version: "3"

services:
  server1:
    build: ./app
    deploy:
      mode: replicated
      replicas: 3
    networks:
      main:

  redis:
    image: redis
    ports:
      - 6379
    networks:
      main:

  router:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    networks:
      main:

networks:
  main:
